### ISSUE TITLE
Would be cool if assert had labels

### ISSUE THREAD

**Issue by sgarza** [azendal/tellurium#10]
var x = false;
spec.assert(x, 'Variable x').toBe(true);
   => Variable x is false toBe true

or something like that.

**Comment by azendal** [comment]
suite.describe('Basic Assertions')(function (describe) {
        describe.specify('should check if value is equal to expected')(function (spec) {
            const value = 5;
            spec.assert(value).withLabel('Check if value is 5').toBe(5);
        });
    });
